/**
 * API Route: GET /api/generate/[projectId]/download
 *
 * Packages all generated files for a project into a zip archive
 * and streams it back as a download.
 * Free tier gets the export with a BoDiGi watermark; paid tiers
 * (starter, pro, enterprise) and admins get clean files.
 */

import { NextRequest, NextResponse } from 'next/server';
import { resolveTier } from '@/lib/trial';
import JSZip from 'jszip';
import { getProject } from '@/lib/agents/pipeline';
import { loadProjectFromSupabase } from '@/lib/supabase/project-store';
import { createServerClient } from '@/lib/supabase/server-client';
import type { ProjectState, GeneratedFile } from '@/lib/agents/types';

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ projectId: string }> }
) {
  const { projectId } = await params;

  // Check authentication
  const supabase = await createServerClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: 'Authentication required' }, { status: 401 });
  }

  // Check tier — free AND trial get watermarked exports, paid gets clean.
  // The trial is a taste of Pro, not a transfer of the asset: clean code
  // only leaves the platform when real money has arrived.
  const { data: profile } = await supabase
    .from('profiles')
    .select('tier, role, is_trial, tier_expires_at')
    .eq('id', user.id)
    .single();

  const tier = resolveTier(profile);
  const isAdmin = profile?.role === 'admin';
  const isPaid = isAdmin || (tier !== 'free' && !profile?.is_trial);

  // Try in-memory first
  const project = getProject(projectId);

  let projectName: string;
  let projectIdea: string;
  let files: GeneratedFile[];
  let specs: unknown;
  let architecture: unknown;

  if (project) {
    projectName = project.state.name;
    projectIdea = project.state.idea;
    files = project.files;
    specs = project.state.specs;
    architecture = project.state.architecture;
  } else {
    // Try Supabase
    const sbProject = await loadProjectFromSupabase(projectId);
    if (!sbProject) {
      return NextResponse.json({ error: 'Project not found' }, { status: 404 });
    }
    projectName = sbProject.state.name;
    projectIdea = sbProject.state.idea;
    files = sbProject.files || [];
    specs = sbProject.state.specs;
    architecture = sbProject.state.architecture;
  }

  if (!files || files.length === 0) {
    return NextResponse.json({ error: 'No files generated yet' }, { status: 400 });
  }

  const zip = new JSZip();

  // Property watermark on every markdown doc — free tier only
  const WATERMARK = `\n\n---\n\n**BoDiGi 2.0's Property** — Generated with the free plan of BoDiGi 2.0 (bodigi2.com). Upgrade to remove this watermark.\n`;

  for (const file of files) {
    const content = !isPaid && file.path.endsWith('.md')
      ? file.content + WATERMARK
      : file.content;
    zip.file(file.path, content);
  }

  // Include manifest
  zip.file('bodigi.manifest.json', JSON.stringify({
    id: projectId,
    name: projectName,
    idea: projectIdea,
    generatedAt: new Date().toISOString(),
    specs,
    architecture,
  }, null, 2));

  // Include setup instructions
  zip.file('SETUP.md', `# ${projectName} — Setup Instructions

## Prerequisites
- Node.js 18+
- npm or yarn

## Environment Variables
Create a \`.env.local\` file in the project root with:

\`\`\`
NEXT_PUBLIC_SUPABASE_URL=your_supabase_url
NEXT_PUBLIC_SUPABASE_ANON_KEY=your_supabase_anon_key
SUPABASE_SERVICE_ROLE_KEY=your_supabase_service_role_key
TELNYX_API_KEY=your_telnyx_api_key
\`\`\`

## Getting API Keys

### Telnyx (AI Provider)
1. Go to telnyx.com and create an account
2. Navigate to API Keys
3. Create a new API key

### Supabase (Database)
1. Go to supabase.com and create an account
2. Create a new project
3. Go to Settings → API
4. Copy the Project URL, Publishable Key, and Secret Key

## Installation
\`\`\`bash
npm install
npm run dev
\`\`\`

## Deployment
Deploy to Vercel, Netlify, or any Node.js hosting platform.
Remember to set all environment variables in your hosting dashboard.

---
Generated by BoDiGi 2.0
`);

  const buffer = await zip.generateAsync({ type: 'nodebuffer' });
  const safeName = projectName.toLowerCase().replace(/[^a-z0-9]+/g, '-') || 'appforge-app';

  return new NextResponse(new Uint8Array(buffer), {
    status: 200,
    headers: {
      'Content-Type': 'application/zip',
      'Content-Disposition': `attachment; filename="${safeName}.zip"`,
      'Content-Length': String(buffer.length),
    },
  });
}
