/**
 * AppForge Architect Agent
 * 
 * Takes the PM agent's specs and designs the system architecture:
 * - Data models (tables, fields, relationships)
 * - API endpoints (REST routes with methods)
 * - Page routes (with auth requirements)
 * - Component tree (pages, layouts, components)
 * - Security model
 * - Scalability notes
 */

import type { ProjectSpecs, ArchitectureDoc, DataModel, ApiEndpoint, PageRoute, ComponentNode } from './types';

export interface ArchitectAgentInput {
  specs: ProjectSpecs;
  idea: string;
}

export interface ArchitectAgentOutput {
  architecture: ArchitectureDoc;
}

export const ARCHITECT_AGENT_SYSTEM_PROMPT = `You are a senior software architect with 15+ years of experience designing scalable, marketplace-ready applications.

Given a project specification, design a complete system architecture. You must define:

1. Data Models: every core table (5-8 max) with fields, types, required flags, and relationships
2. API Endpoints: every REST endpoint (10-16 max) with method, path, description, and auth flag
3. Page Routes: every page (8-12 max) with path, name, auth flag, and role
4. Component Tree: the React hierarchy — top-level pages/layouts only, 3-6 nodes, max depth 3
5. Security Model: 2-3 sentences on auth, authorization, data protection
6. Scalability Notes: 2-3 sentences

INTEGRATIONS: The spec may include requiredApis (third-party services the app needs, e.g. Stripe, Resend, OpenRouter, Google Maps). For each one, include the API endpoints that wrap it (e.g. /api/billing/checkout, /api/ai/chat) and note the integration in the overview. Third-party keys must live in environment variables referenced server-side — never in client components. If the spec calls for AI agents or multi-agent workflows, design a server-side agent layer (orchestrator + specialist modules) with endpoints per agent action, streaming where responses are long.

Respond ONLY in valid, COMPACT JSON — no whitespace, no indentation, no comments. Keep field descriptions terse (2-5 words). This JSON must parse; favor completeness of structure over verbosity of description.

Structure:
{"overview":"...","dataModels":[{"name":"users","fields":[{"name":"id","type":"uuid","required":true}],"relationships":["has_many:projects"]}],"apiEndpoints":[{"method":"POST","path":"/api/auth/signup","description":"Create account","authRequired":false}],"pageRoutes":[{"path":"/","name":"Landing","authRequired":false,"role":"public"}],"componentTree":[{"name":"RootLayout","type":"layout","children":[{"name":"Navbar","type":"component","children":[]}]}],"securityModel":"...","scalabilityNotes":"..."}`;

export function buildArchitectPrompt(input: ArchitectAgentInput): string {
  return `Design the system architecture for this application:

Project: ${input.idea}
Target Audience: ${input.specs.targetAudience}
Features: ${input.specs.features.map(f => f.name).join(', ')}
Tech Stack: ${JSON.stringify(input.specs.techStack)}
Marketplace: ${input.specs.marketplace}
Required integrations: ${(input.specs.requiredApis || []).map(a => `${a.provider} (${a.reason}; env: ${a.envVars.join(', ')})`).join('; ') || 'Supabase only'}

Respond with the JSON architecture only.`;
}

/**
 * Parse the architect agent's JSON response into a typed ArchitectureDoc.
 * Includes fallbacks for missing fields.
 */
export function parseArchitectResponse(response: string): ArchitectAgentOutput {
  let parsed: ArchitectureDoc;

  // Strip markdown code fences that models often wrap around JSON
  let cleaned = response.trim();
  if (cleaned.startsWith('```')) {
    cleaned = cleaned.replace(/^```(?:json)?\s*/i, '').replace(/```\s*$/, '');
  }

  try {
    parsed = JSON.parse(cleaned);
  } catch {
    // If JSON parsing fails, try to extract JSON from the response
    const jsonMatch = cleaned.match(/\{[\s\S]*\}/);
    if (jsonMatch) {
      parsed = JSON.parse(jsonMatch[0]);
    } else {
      throw new Error('Architect agent returned invalid JSON');
    }
  }

  return {
    architecture: {
      overview: parsed.overview || 'Architecture generated by AI',
      dataModels: parsed.dataModels || [],
      apiEndpoints: parsed.apiEndpoints || [],
      pageRoutes: parsed.pageRoutes || [],
      componentTree: parsed.componentTree || [],
      securityModel: parsed.securityModel || '',
      scalabilityNotes: parsed.scalabilityNotes || '',
    },
  };
}

export function generateDefaultArchitecture(specs: ProjectSpecs, idea: string): ArchitectAgentOutput {
  const dataModels: DataModel[] = [
    {
      name: 'users',
      fields: [
        { name: 'id', type: 'uuid', required: true },
        { name: 'email', type: 'string', required: true },
        { name: 'password_hash', type: 'string', required: true },
        { name: 'name', type: 'string', required: false },
        { name: 'role', type: 'enum(user, admin)', required: true },
        { name: 'created_at', type: 'timestamp', required: true },
        { name: 'updated_at', type: 'timestamp', required: true },
      ],
      relationships: ['has_many:projects', 'has_many:subscriptions'],
    },
    {
      name: 'projects',
      fields: [
        { name: 'id', type: 'uuid', required: true },
        { name: 'user_id', type: 'uuid', required: true, references: 'users.id' },
        { name: 'name', type: 'string', required: true },
        { name: 'description', type: 'text', required: false },
        { name: 'status', type: 'enum(active, archived)', required: true },
        { name: 'created_at', type: 'timestamp', required: true },
      ],
      relationships: ['belongs_to:users', 'has_many:tasks'],
    },
    {
      name: 'tasks',
      fields: [
        { name: 'id', type: 'uuid', required: true },
        { name: 'project_id', type: 'uuid', required: true, references: 'projects.id' },
        { name: 'title', type: 'string', required: true },
        { name: 'description', type: 'text', required: false },
        { name: 'status', type: 'enum(todo, in_progress, done)', required: true },
        { name: 'priority', type: 'enum(low, medium, high)', required: true },
        { name: 'due_date', type: 'date', required: false },
        { name: 'created_at', type: 'timestamp', required: true },
      ],
      relationships: ['belongs_to:projects'],
    },
    {
      name: 'subscriptions',
      fields: [
        { name: 'id', type: 'uuid', required: true },
        { name: 'user_id', type: 'uuid', required: true, references: 'users.id' },
        { name: 'stripe_customer_id', type: 'string', required: true },
        { name: 'stripe_subscription_id', type: 'string', required: false },
        { name: 'plan', type: 'enum(free, pro, enterprise)', required: true },
        { name: 'status', type: 'enum(active, canceled, past_due)', required: true },
        { name: 'current_period_end', type: 'timestamp', required: false },
      ],
      relationships: ['belongs_to:users'],
    },
  ];

  const apiEndpoints: ApiEndpoint[] = [
    { method: 'POST', path: '/api/auth/signup', description: 'Create a new account', authRequired: false },
    { method: 'POST', path: '/api/auth/login', description: 'Authenticate user', authRequired: false },
    { method: 'POST', path: '/api/auth/logout', description: 'End session', authRequired: true },
    { method: 'GET', path: '/api/projects', description: 'List user projects', authRequired: true },
    { method: 'POST', path: '/api/projects', description: 'Create a project', authRequired: true },
    { method: 'GET', path: '/api/projects/:id', description: 'Get project details', authRequired: true },
    { method: 'PUT', path: '/api/projects/:id', description: 'Update project', authRequired: true },
    { method: 'DELETE', path: '/api/projects/:id', description: 'Delete project', authRequired: true },
    { method: 'GET', path: '/api/projects/:id/tasks', description: 'List tasks in project', authRequired: true },
    { method: 'POST', path: '/api/projects/:id/tasks', description: 'Create task', authRequired: true },
    { method: 'PUT', path: '/api/tasks/:id', description: 'Update task', authRequired: true },
    { method: 'DELETE', path: '/api/tasks/:id', description: 'Delete task', authRequired: true },
    { method: 'GET', path: '/api/admin/users', description: 'Admin: list all users', authRequired: true },
    { method: 'PUT', path: '/api/admin/users/:id', description: 'Admin: update user role', authRequired: true },
    { method: 'POST', path: '/api/billing/subscribe', description: 'Create Stripe subscription', authRequired: true },
    { method: 'POST', path: '/api/billing/webhook', description: 'Stripe webhook handler', authRequired: false },
  ];

  const pageRoutes: PageRoute[] = [
    { path: '/', name: 'Landing', authRequired: false, role: 'public' },
    { path: '/login', name: 'Login', authRequired: false, role: 'public' },
    { path: '/signup', name: 'Sign Up', authRequired: false, role: 'public' },
    { path: '/dashboard', name: 'Dashboard', authRequired: true, role: 'user' },
    { path: '/projects/:id', name: 'Project Detail', authRequired: true, role: 'user' },
    { path: '/settings', name: 'Settings', authRequired: true, role: 'user' },
    { path: '/billing', name: 'Billing', authRequired: true, role: 'user' },
    { path: '/admin', name: 'Admin Panel', authRequired: true, role: 'admin' },
    { path: '/admin/users', name: 'User Management', authRequired: true, role: 'admin' },
  ];

  const componentTree: ComponentNode[] = [
    {
      name: 'RootLayout',
      type: 'layout',
      children: [
        { name: 'Navbar', type: 'component', children: [] },
        { name: 'Footer', type: 'component', children: [] },
      ],
    },
    {
      name: 'LandingPage',
      type: 'page',
      children: [
        { name: 'HeroSection', type: 'component', children: [] },
        { name: 'FeaturesSection', type: 'component', children: [] },
        { name: 'CTASection', type: 'component', children: [] },
      ],
    },
    {
      name: 'DashboardLayout',
      type: 'layout',
      children: [
        { name: 'Sidebar', type: 'component', children: [] },
        { name: 'DashboardNav', type: 'component', children: [] },
      ],
    },
    {
      name: 'DashboardPage',
      type: 'page',
      children: [
        { name: 'ProjectList', type: 'component', children: [
          { name: 'ProjectCard', type: 'component', children: [] },
        ] },
        { name: 'StatsOverview', type: 'component', children: [] },
      ],
    },
    {
      name: 'AdminPage',
      type: 'page',
      children: [
        { name: 'UserTable', type: 'component', children: [] },
        { name: 'SystemStats', type: 'component', children: [] },
      ],
    },
  ];

  return {
    architecture: {
      overview: `A full-stack web application built with Next.js 15 (App Router) and Supabase (PostgreSQL). The architecture follows a feature-centric organization with route groups for (marketing), (dashboard), and (admin). Authentication is handled via Supabase Auth with role-based access control (user/admin). The API layer uses Next.js server actions and API routes with Zod validation. Stripe handles subscription billing with webhook-based lifecycle management.`,
      dataModels,
      apiEndpoints,
      pageRoutes,
      componentTree,
      securityModel: 'Authentication via Supabase Auth (email/password + OAuth). JWT-based sessions with refresh tokens. Role-based access control (RBAC) with user and admin roles. Row-level security (RLS) policies on all database tables. API routes validate input with Zod schemas. CORS configured for allowed origins only. Rate limiting on auth endpoints.',
      scalabilityNotes: 'Serverless deployment on Vercel with edge functions for API routes. Supabase handles database scaling with connection pooling. Static pages cached at the edge. ISR for semi-dynamic content. Image optimization via next/image. Horizontal scaling via stateless API design.',
    },
  };
}
